[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
    "npm ci --no-audit --no-fund --prefer-offline || npm install --no-audit --no-fund --prefer-offline"
]

[phases.build]
cmds = [
    "chmod +x railway-build.sh",
    "./railway-build.sh"
]

[start]
cmd = "npm start" 