[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
buildCommand = "./railway-build.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
